import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import { Box, IconButton, Typography } from "@mui/joy";
import * as React from "react";
import { Toaster } from "sonner";
import { Provider } from "../components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <Provider>
      <html lang="en">
        <body>
          <Toaster richColors position="top-right" />
          <ThemeRegistry>{children}</ThemeRegistry>
        </body>
      </html>
    </Provider>
  );
}
