import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import { Box, IconButton, Typography } from "@mui/joy";
import * as React from "react";
import { Toaster } from "sonner";
import { Provider } from "../components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Provider>{children}</Provider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
